<?php
require_once '../../../../libs/composer/vendor/autoload.php';

class ilObjLTIAdministrationTest extends PHPUnit_Framework_TestCase
{
	protected  $webdriver;

	protected $url = "http://localhost/~leifos/ILIAS_trunk/trunk/";

	public function setUp()
	{
		$capabilities = [
			\WebDriverCapabilityType::BROWSER_NAME=>'chrome',
			\WebDriverCapabilityType::BROWSER_NAME=>'firefox'
		];

		$host = 'http://localhost:4444/wd/hub';

		$this->webdriver = RemoteWebDriver::create($host, $capabilities);

		$this->webdriver->get($this->url);

	}

	public function testCreate()
	{
		$this->webdriver->findElement(WebDriverBy::id('username'))->click()->sendKeys("root");

		$this->webdriver->findElement(WebDriverBy::id('password'))->click()->sendKeys("homer");

		$this->webdriver->findElement(WebDriverBy::name('cmd[doStandardAuthentication]'))->click();
		//$this->webdriver->manage()->timeouts()->implicitlyWait = 6;
		sleep(4);

		$this->webdriver->findElement(WebDriverBy::id('mm_adm_tr'))->click();
		//$this->webdriver->manage()->timeouts()->implicitlyWait = 4;
		sleep(4);


		$this->webdriver->findElement(WebDriverBy::id('mm_adm_ltis'))->click();
		sleep(2);


		$this->webdriver->findElement(WebDriverBy::id('tab_consumers'))->click();
		sleep(2);

		$this->webdriver->findElement(WebDriverBy::partialLinkText("Create Consumer"))->click();
		sleep(2);

		$title = $this->webdriver->findElement(WebDriverBy::id('title'));
		$title->click();
		$title->sendKeys("ST Title");

		$desc = $this->webdriver->findElement(WebDriverBy::id('description'));
		$desc->click();
		$desc->sendKeys("ST Description");

		$prefix = $this->webdriver->findElement(WebDriverBy::id('prefix'));
		$prefix->click();
		$prefix->sendKeys("STK");

		$key = $this->webdriver->findElement(WebDriverBy::id('key'));
		$key->click();
		$key->sendKeys("ThisIsTheKey");

		$secret = $this->webdriver->findElement(WebDriverBy::id('secret'));
		$secret->click();
		$secret->sendKeys("laksjdfiuaosifjlaksdf");

		$active = $this->webdriver->findElement(WebDriverBy::id('active'));
		$active->click();

		$svy = $this->webdriver->findElement(WebDriverBy::id('types_svy'));
		$svy->click();


		$this->webdriver->findElement(WebDriverBy::name('cmd[createLTIConsumer]'))->submit();

	}

	public function testEdit()
	{
		$this->webdriver->findElement(WebDriverBy::id('username'))->click()->sendKeys("root");

		$this->webdriver->findElement(WebDriverBy::id('password'))->click()->sendKeys("homer");

		$this->webdriver->findElement(WebDriverBy::name('cmd[doStandardAuthentication]'))->click();
		//$this->webdriver->manage()->timeouts()->implicitlyWait = 6;
		sleep(4);

		$this->webdriver->findElement(WebDriverBy::id('mm_adm_tr'))->click();
		//$this->webdriver->manage()->timeouts()->implicitlyWait = 4;
		sleep(4);


		$this->webdriver->findElement(WebDriverBy::id('mm_adm_ltis'))->click();
		sleep(2);


		$this->webdriver->findElement(WebDriverBy::id('tab_consumers'))->click();
		sleep(2);

		$this->webdriver->findElement(WebDriverBy::partialLinkText("Actions"))->click();
		sleep(2);

	}

	public function tearDown()
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

}